In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.datasets import fetch_20newsgroups

In [17]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
t=fetch_20newsgroups(subset='train',shuffle=True)

In [38]:
t.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [67]:
v=CountVectorizer()
x=v.fit_transform(t.data)
b=BernoulliNB()
b_t=b.fit(x,t.target)

In [55]:
print(v.get_feature_names_out())
small_x = x[:10]  # Or [:10, :1000] if you're interested in some features
y = small_x.toarray()
print(y)


['00' '000' '0000' ... 'íålittin' 'ñaustin' 'ýé']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [60]:
y=b.predict(x)
y

array([7, 4, 4, ..., 3, 1, 6])

In [83]:
from sklearn.metrics import accuracy_score
d=accuracy_score(t.target,y)
d

0.7821283365741559